countryNameToCode = {
  "Bangladesh": "BD",
  "Belgium": "BE",
  "Burkina Faso": "BF",
  "Bulgaria": "BG",
  "Bosnia and Herzegovina": "BA",
  "Barbados": "BB",
  "Wallis and Futuna": "WF",
  "Saint Barthelemy": "BL",
  "Bermuda": "BM",
  "Brunei": "BN",
  "Bolivia": "BO",
  "Bahrain": "BH",
  "Burundi": "BI",
  "Benin": "BJ",
  "Bhutan": "BT",
  "Jamaica": "JM",
  "Bouvet Island": "BV",
  "Botswana": "BW",
  "Samoa": "WS",
  "Bonaire, Saint Eustatius and Saba ": "BQ",
  "Brazil": "BR",
  "Bahamas": "BS",
  "Jersey": "JE",
  "Belarus": "BY",
  "Belize": "BZ",
  "Russia": "RU",
  "Rwanda": "RW",
  "Serbia": "RS",
  "East Timor": "TL",
  "Reunion": "RE",
  "Turkmenistan": "TM",
  "Tajikistan": "TJ",
  "Romania": "RO",
  "Tokelau": "TK",
  "Guinea-Bissau": "GW",
  "Guam": "GU",
  "Guatemala": "GT",
  "South Georgia and the South Sandwich Islands": "GS",
  "Greece": "GR",
  "Equatorial Guinea": "GQ",
  "Guadeloupe": "GP",
  "Japan": "JP",
  "Guyana": "GY",
  "Guernsey": "GG",
  "French Guiana": "GF",
  "Georgia": "GE",
  "Grenada": "GD",
  "United Kingdom": "GB",
  "Gabon": "GA",
  "El Salvador": "SV",
  "Guinea": "GN",
  "Gambia": "GM",
  "Greenland": "GL",
  "Gibraltar": "GI",
  "Ghana": "GH",
  "Oman": "OM",
  "Tunisia": "TN",
  "Jordan": "JO",
  "Croatia": "HR",
  "Haiti": "HT",
  "Hungary": "HU",
  "Hong Kong": "HK",
  "Honduras": "HN",
  "Heard Island and McDonald Islands": "HM",
  "Venezuela": "VE",
  "Puerto Rico": "PR",
  "Palestinian Territory": "PS",
  "Palau": "PW",
  "Portugal": "PT",
  "Svalbard and Jan Mayen": "SJ",
  "Paraguay": "PY",
  "Iraq": "IQ",
  "Panama": "PA",
  "French Polynesia": "PF",
  "Papua New Guinea": "PG",
  "Peru": "PE",
  "Pakistan": "PK",
  "Philippines": "PH",
  "Pitcairn": "PN",
  "Poland": "PL",
  "Saint Pierre and Miquelon": "PM",
  "Zambia": "ZM",
  "Western Sahara": "EH",
  "Estonia": "EE",
  "Egypt": "EG",
  "South Africa": "ZA",
  "Ecuador": "EC",
  "Italy": "IT",
  "Vietnam": "VN",
  "Solomon Islands": "SB",
  "Ethiopia": "ET",
  "Somalia": "SO",
  "Zimbabwe": "ZW",
  "Saudi Arabia": "SA",
  "Spain": "ES",
  "Eritrea": "ER",
  "Montenegro": "ME",
  "Moldova": "MD",
  "Madagascar": "MG",
  "Saint Martin": "MF",
  "Morocco": "MA",
  "Monaco": "MC",
  "Uzbekistan": "UZ",
  "Myanmar": "MM",
  "Mali": "ML",
  "Macao": "MO",
  "Mongolia": "MN",
  "Marshall Islands": "MH",
  "Macedonia": "MK",
  "Mauritius": "MU",
  "Malta": "MT",
  "Malawi": "MW",
  "Maldives": "MV",
  "Martinique": "MQ",
  "Northern Mariana Islands": "MP",
  "Montserrat": "MS",
  "Mauritania": "MR",
  "Isle of Man": "IM",
  "Uganda": "UG",
  "Tanzania": "TZ",
  "Malaysia": "MY",
  "Mexico": "MX",
  "Israel": "IL",
  "France": "FR",
  "British Indian Ocean Territory": "IO",
  "Saint Helena": "SH",
  "Finland": "FI",
  "Fiji": "FJ",
  "Falkland Islands": "FK",
  "Micronesia": "FM",
  "Faroe Islands": "FO",
  "Nicaragua": "NI",
  "Netherlands": "NL",
  "Norway": "NO",
  "Namibia": "NA",
  "Vanuatu": "VU",
  "New Caledonia": "NC",
  "Niger": "NE",
  "Norfolk Island": "NF",
  "Nigeria": "NG",
  "New Zealand": "NZ",
  "Nepal": "NP",
  "Nauru": "NR",
  "Niue": "NU",
  "Cook Islands": "CK",
  "Kosovo": "XK",
  "Ivory Coast": "CI",
  "Switzerland": "CH",
  "Colombia": "CO",
  "China": "CN",
  "Cameroon": "CM",
  "Chile": "CL",
  "Cocos Islands": "CC",
  "Canada": "CA",
  "Republic of the Congo": "CG",
  "Central African Republic": "CF",
  "Democratic Republic of the Congo": "CD",
  "Czech Republic": "CZ",
  "Cyprus": "CY",
  "Christmas Island": "CX",
  "Costa Rica": "CR",
  "Curacao": "CW",
  "Cape Verde": "CV",
  "Cuba": "CU",
  "Swaziland": "SZ",
  "Syria": "SY",
  "Sint Maarten": "SX",
  "Kyrgyzstan": "KG",
  "Kenya": "KE",
  "South Sudan": "SS",
  "Suriname": "SR",
  "Kiribati": "KI",
  "Cambodia": "KH",
  "Saint Kitts and Nevis": "KN",
  "Comoros": "KM",
  "Sao Tome and Principe": "ST",
  "Slovakia": "SK",
  "South Korea": "KR",
  "Slovenia": "SI",
  "North Korea": "KP",
  "Kuwait": "KW",
  "Senegal": "SN",
  "San Marino": "SM",
  "Sierra Leone": "SL",
  "Seychelles": "SC",
  "Kazakhstan": "KZ",
  "Cayman Islands": "KY",
  "Singapore": "SG",
  "Sweden": "SE",
  "Sudan": "SD",
  "Dominican Republic": "DO",
  "Dominica": "DM",
  "Djibouti": "DJ",
  "Denmark": "DK",
  "British Virgin Islands": "VG",
  "Germany": "DE",
  "Yemen": "YE",
  "Algeria": "DZ",
  "United States": "US",
  "Uruguay": "UY",
  "Mayotte": "YT",
  "United States Minor Outlying Islands": "UM",
  "Lebanon": "LB",
  "Saint Lucia": "LC",
  "Laos": "LA",
  "Tuvalu": "TV",
  "Taiwan": "TW",
  "Trinidad and Tobago": "TT",
  "Turkey": "TR",
  "Sri Lanka": "LK",
  "Liechtenstein": "LI",
  "Latvia": "LV",
  "Tonga": "TO",
  "Lithuania": "LT",
  "Luxembourg": "LU",
  "Liberia": "LR",
  "Lesotho": "LS",
  "Thailand": "TH",
  "French Southern Territories": "TF",
  "Togo": "TG",
  "Chad": "TD",
  "Turks and Caicos Islands": "TC",
  "Libya": "LY",
  "Vatican": "VA",
  "Saint Vincent and the Grenadines": "VC",
  "United Arab Emirates": "AE",
  "Andorra": "AD",
  "Antigua and Barbuda": "AG",
  "Afghanistan": "AF",
  "Anguilla": "AI",
  "U.S. Virgin Islands": "VI",
  "Iceland": "IS",
  "Iran": "IR",
  "Armenia": "AM",
  "Albania": "AL",
  "Angola": "AO",
  "Antarctica": "AQ",
  "American Samoa": "AS",
  "Argentina": "AR",
  "Australia": "AU",
  "Austria": "AT",
  "Aruba": "AW",
  "India": "IN",
  "Aland Islands": "AX",
  "Azerbaijan": "AZ",
  "Ireland": "IE",
  "Indonesia": "ID",
  "Ukraine": "UA",
  "Qatar": "QA",
  "Mozambique": "MZ"
};


koreaNameToCode = {
  "Gangwon":"강원",
  "Gyeonggi":"경기",
  "Seoul":"서울",
  "Incheon":"인천",
  "South Chungcheong":"충남",
  "North Chungcheong":"충북",
  "Sejong":"세종",
  "Daejeon":"대전",
  "North Gyeongsang":"경북",
  "Daegu":"대구",
  "North Jeolla":"전북",
  "South Jeolla":"전남",
  "Gwangju":"광주",
  "South Gyeongsang":"경남",
  "Ulsan":"울산",
  "Busan":"부산",
  "Jeju":"제주"
};
g_koreaNameToCode = {
'KR-11':"서울",
'KR-26':"부산",
'KR-27':"대구",
'KR-30':"대전",
'KR-29':"광주",
'KR-28':"인천",
'KR-31':"울산",
'KR-43':"충북",
'KR-44':"충남",
'KR-42':"강원",
'KR-41':"경기",
'KR-47':"경북",
'KR-48':"경남",
'KR-49':"제주",
'KR-45':"전북",
'KR-46':"전남"
};
gg_koreaNameToCode = {
"서울":'KR-11',
"부산":'KR-26',
"대구":'KR-27',
"대전":'KR-30',
"광주":'KR-29',
"인천":'KR-28',
"울산":'KR-31',
"충북":'KR-43',
"충남":'KR-44',
"강원":'KR-42',
"경기":'KR-41',
"경북":'KR-47',
"경남":'KR-48',
"제주":'KR-49',
"전북":'KR-45',
"전남":'KR-46'
};


countryKoreaName = {
  "Bangladesh": "방글라데시(BD)",
  "Belgium": "벨기에(BE)",
  "Burkina Faso": "부르키나 파소(BF)",
  "Bulgaria": "불가리아(BG)",
  "Bosnia and Herzegovina": "보스니아 헤르체고비나(BA)",
  "Barbados": "바베이도스(BB)",
  "Wallis and Futuna": "왈리스 푸투나(WF)",
  "Saint Barthelemy": "생바르텔레미(BL)",
  "Bermuda": "버뮤다(BM)",
  "Brunei": "브루나이(BN)",
  "Bolivia": "볼리비아(BO)",
  "Bahrain": "바레인(BH)",
  "Burundi": "부룬디(BI)",
  "Benin": "베냉(BJ)",
  "Bhutan": "부탄(BT)",
  "Jamaica": "자메이카(JM)",
  "Bouvet Island": "부베 섬(BV)",
  "Botswana": "보츠와나(BW)",
  "Samoa": "사모아(WS)",
  "Bonaire, Saint Eustatius and Saba": "카리브 네덜란드(BQ)",
  "Brazil": "브라질(BR)",
  "Bahamas": "바하마(BS)",
  "Jersey": "저지섬(JE)",
  "Belarus": "벨로루시(BY)",
  "Belize": "벨리즈(BZ)",
  "Russia": "러시아(RU)",
  "Rwanda": "르완다(RW)",
  "Serbia": "세르비아(RS)",
  "East Timor": "동티모르(TL)",
  "Reunion": "레위니옹(RE)",
  "Turkmenistan": "투르크메니스탄(TM)",
  "Tajikistan": "타지키스탄(TJ)",
  "Romania": "루마니아(RO)",
  "Tokelau": "토켈라우(TK)",
  "Guinea-Bissau": "기니비사우(GW)",
  "Guam": "괌(GU)",
  "Guatemala": "과테말라(GT)",
  "South Georgia and the South Sandwich Islands": "(GS)",
  "Greece": "(GR)",
  "Equatorial Guinea": "(GQ)",
  "Guadeloupe": "(GP)",
  "Japan": "(JP)",
  "Guyana": "(GY)",
  "Guernsey": "(GG)",
  "French Guiana": "(GF)",
  "Georgia": "(GE)",
  "Grenada": "(GD)",
  "United Kingdom": "(GB)",
  "Gabon": "(GA)",
  "El Salvador": "(SV)",
  "Guinea": "(GN)",
  "Gambia": "(GM)",
  "Greenland": "(GL)",
  "Gibraltar": "(GI)",
  "Ghana": "(GH)",
  "Oman": "(OM)",
  "Tunisia": "(TN)",
  "Jordan": "(JO)",
  "Croatia": "(HR)",
  "Haiti": "(HT)",
  "Hungary": "(HU)",
  "Hong Kong": "(HK)",
  "Honduras": "(HN)",
  "Heard Island and McDonald Islands": "(HM)",
  "Venezuela": "(VE)",
  "Puerto Rico": "(PR)",
  "Palestinian Territory": "(PS)",
  "Palau": "(PW)",
  "Portugal": "(PT)",
  "Svalbard and Jan Mayen": "(SJ)",
  "Paraguay": "(PY)",
  "Iraq": "(IQ)",
  "Panama": "(PA)",
  "French Polynesia": "(PF)",
  "Papua New Guinea": "(PG)",
  "Peru": "(PE)",
  "Pakistan": "(PK)",
  "Philippines": "(PH)",
  "Pitcairn": "(PN)",
  "Poland": "(PL)",
  "Saint Pierre and Miquelon": "(PM)",
  "Zambia": "(ZM)",
  "Western Sahara": "(EH)",
  "Estonia": "(EE)",
  "Egypt": "(EG)",
  "South Africa": "(ZA)",
  "Ecuador": "(EC)",
  "Italy": "(IT)",
  "Vietnam": "(VN)",
  "Solomon Islands": "(SB)",
  "Ethiopia": "(ET)",
  "Somalia": "(SO)",
  "Zimbabwe": "(ZW)",
  "Saudi Arabia": "(SA)",
  "Spain": "(ES)",
  "Eritrea": "(ER)",
  "Montenegro": "(ME)",
  "Moldova": "(MD)",
  "Madagascar": "(MG)",
  "Saint Martin": "(MF)",
  "Morocco": "(MA)",
  "Monaco": "(MC)",
  "Uzbekistan": "(UZ)",
  "Myanmar": "(MM)",
  "Mali": "(ML)",
  "Macao": "(MO)",
  "Mongolia": "(MN)",
  "Marshall Islands": "(MH)",
  "Macedonia": "(MK)",
  "Mauritius": "(MU)",
  "Malta": "(MT)",
  "Malawi": "(MW)",
  "Maldives": "(MV)",
  "Martinique": "(MQ)",
  "Northern Mariana Islands": "(MP)",
  "Montserrat": "(MS)",
  "Mauritania": "(MR)",
  "Isle of Man": "(IM)",
  "Uganda": "(UG)",
  "Tanzania": "(TZ)",
  "Malaysia": "(MY)",
  "Mexico": "(MX)",
  "Israel": "(IL)",
  "France": "(FR)",
  "British Indian Ocean Territory": "(IO)",
  "Saint Helena": "(SH)",
  "Finland": "(FI)",
  "Fiji": "(FJ)",
  "Falkland Islands": "(FK)",
  "Micronesia": "(FM)",
  "Faroe Islands": "(FO)",
  "Nicaragua": "(NI)",
  "Netherlands": "(NL)",
  "Norway": "(NO)",
  "Namibia": "(NA)",
  "Vanuatu": "(VU)",
  "New Caledonia": "(NC)",
  "Niger": "(NE)",
  "Norfolk Island": "(NF)",
  "Nigeria": "(NG)",
  "New Zealand": "(NZ)",
  "Nepal": "(NP)",
  "Nauru": "(NR)",
  "Niue": "(NU)",
  "Cook Islands": "(CK)",
  "Kosovo": "(XK)",
  "Ivory Coast": "(CI)",
  "Switzerland": "(CH)",
  "Colombia": "(CO)",
  "China": "(CN)",
  "Cameroon": "(CM)",
  "Chile": "(CL)",
  "Cocos Islands": "(CC)",
  "Canada": "(CA)",
  "Republic of the Congo": "(CG)",
  "Central African Republic": "(CF)",
  "Democratic Republic of the Congo": "(CD)",
  "Czech Republic": "(CZ)",
  "Cyprus": "(CY)",
  "Christmas Island": "(CX)",
  "Costa Rica": "(CR)",
  "Curacao": "(CW)",
  "Cape Verde": "(CV)",
  "Cuba": "(CU)",
  "Swaziland": "(SZ)",
  "Syria": "(SY)",
  "Sint Maarten": "(SX)",
  "Kyrgyzstan": "(KG)",
  "Kenya": "(KE)",
  "South Sudan": "(SS)",
  "Suriname": "(SR)",
  "Kiribati": "(KI)",
  "Cambodia": "(KH)",
  "Saint Kitts and Nevis": "(KN)",
  "Comoros": "(KM)",
  "Sao Tome and Principe": "(ST)",
  "Slovakia": "(SK)",
  "South Korea": "(KR)",
  "Slovenia": "(SI)",
  "North Korea": "(KP)",
  "Kuwait": "(KW)",
  "Senegal": "(SN)",
  "San Marino": "(SM)",
  "Sierra Leone": "(SL)",
  "Seychelles": "(SC)",
  "Kazakhstan": "(KZ)",
  "Cayman Islands": "(KY)",
  "Singapore": "(SG)",
  "Sweden": "(SE)",
  "Sudan": "(SD)",
  "Dominican Republic": "(DO)",
  "Dominica": "(DM)",
  "Djibouti": "(DJ)",
  "Denmark": "(DK)",
  "British Virgin Islands": "(VG)",
  "Germany": "(DE)",
  "Yemen": "(YE)",
  "Algeria": "(DZ)",
  "United States": "(US)",
  "Uruguay": "(UY)",
  "Mayotte": "(YT)",
  "United States Minor Outlying Islands": "(UM)",
  "Lebanon": "(LB)",
  "Saint Lucia": "(LC)",
  "Laos": "(LA)",
  "Tuvalu": "(TV)",
  "Taiwan": "(TW)",
  "Trinidad and Tobago": "(TT)",
  "Turkey": "(TR)",
  "Sri Lanka": "(LK)",
  "Liechtenstein": "(LI)",
  "Latvia": "(LV)",
  "Tonga": "(TO)",
  "Lithuania": "(LT)",
  "Luxembourg": "(LU)",
  "Liberia": "(LR)",
  "Lesotho": "(LS)",
  "Thailand": "(TH)",
  "French Southern Territories": "(TF)",
  "Togo": "(TG)",
  "Chad": "(TD)",
  "Turks and Caicos Islands": "(TC)",
  "Libya": "(LY)",
  "Vatican": "(VA)",
  "Saint Vincent and the Grenadines": "(VC)",
  "United Arab Emirates": "(AE)",
  "Andorra": "(AD)",
  "Antigua and Barbuda": "(AG)",
  "Afghanistan": "(AF)",
  "Anguilla": "(AI)",
  "U.S. Virgin Islands": "(VI)",
  "Iceland": "(IS)",
  "Iran": "(IR)",
  "Armenia": "(AM)",
  "Albania": "(AL)",
  "Angola": "(AO)",
  "Antarctica": "(AQ)",
  "American Samoa": "(AS)",
  "Argentina": "(AR)",
  "Australia": "(AU)",
  "Austria": "(AT)",
  "Aruba": "(AW)",
  "India": "(IN)",
  "Aland Islands": "(AX)",
  "Azerbaijan": "(AZ)",
  "Ireland": "(IE)",
  "Indonesia": "(ID)",
  "Ukraine": "(UA)",
  "Qatar": "(QA)",
  "Mozambique": "(MZ)"
};
